// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://myspriwgycyymelgyttu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im15c3ByaXdneWN5eW1lbGd5dHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjE4NjEsImV4cCI6MjA3MjUzNzg2MX0.fGCeEy7nYweB1wmFloShIfTmJaj2_nV_SjgtLMlQ1vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});